version: 2

sources:
  - name: gmail_rawdata
    database: wpp-dev-test 
    schema: gmail_rawdata
    tables:
      - name: adv_table
        description: "The raw CSV data loaded into BigQuery"

models:
  - name: staging_data
    description: "in staging data formatting fixed, nulls replaced, and duplicates removed."
    columns:
      - name: ad_id
        description: "The unique identifier for each row"
        tests:
          - unique
          - not_null 
      - name: platform
        tests:
          - not_null
          - accepted_values:
              values: ['google ads', 'meta ads', 'tiktok ads'] 
      - name: campaign_name
        tests:
          - not_null
      - name: conversions
        description: "Null values are forced to 0 value."
        tests:
          - not_null

  - name: performance_data
    description: "Daily aggregated campaign performance."
    columns:
      - name: ad_date
        description: "ad_date should not be null."
        tests:
          - not_null